const config = {
  vnp_TmnCode: 'Y0ZQ6C33',
  vnp_HashSecret: 'WPGPRYLAUYYZNOADEPVQLVMUPFSGQGEO',
  vnp_Url: 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html',
  returnUrl: 'https://travel-fe.vercel.app/VnPayReturn',
  // "vnp_Locale": "vn",
  // "vnp_BankCode": "NCB",
  // "vnp_OrderInfo": "Thanh toan don hang",
  // "vnp_Amount": "100000",
  // "vnp_Command": "pay",
  // "vnp_TimeStamp": "20180712091212",
  // "vnp_Version": "2.0.0",
  // "vnp_ReturnUrl": "http://sandbox.vnpayment.vn/tryitnow/Home/VnPayReturn",
  // vnp_IpAddr: 'http://sandbox.vnpayment.vn/tryitnow/Home/VnPayReturn',
  // "vnp_CreateDate": "20180712091212",
  // "vnp_OrderType": "1",
  // "vnp_Imei": ",
  manage_url: 'https://sandbox.vnpayment.vn/merchantv2/',
};
module.exports = config;
